/* Main.c file generated by New Project wizard
 *
 * Created:   周三 6月 1 2022
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit key=P3^2;
#define  uchar unsigned char
uchar button_ctr=0;

void delay(unsigned int i){
   unsigned int j;
   for(;i>0;i--)
   for(j=0;j<125;j++){;}
}
void LED_ON(){
   P1=0X0F;
}

void BUT_OFF(){
   key=1;
}

//TCON>IE>IP
void T0_INIT(){
   TMOD=0X01;//manner;GATE CT M1 M0
   TH0=(65535-50000)/256;
   TL0=(65535-50000)%256;
   TF0=0;
   TR0=1;

}

void T1_INIT(){
   TMOD = 0Xd1;
   TH1=(65535-3)/256;
   TL1=(65535-3)%256;
   TR1=1;
}

void TCON_INIT(){
   IE0=1;	//REQUEST IRQ FLAG(TCON)
   IT0=0;      //trigger mode (TCON)
}

void IE_INIT(){
   EX0=1;      //EXTERN (IE)
   ET0=1;      //enable T0(IE)
   ET1=1;      //enable T1(IE)
}

void IRQ_PRIORITY(){
   PX0=1;//INT0
   PT1=1;//T1 ctr
   PT0=0;//T0 timer
}

void IRQ_INIT(){
   TCON_INIT();
   IE_INIT();
   IRQ_PRIORITY(); //IP
   T0_INIT();
   T1_INIT();
   EA=1;	      //Enable interupt
}

void change_flow(){
   uchar m;
   EX0=0;
   for(m=0;m<5;m++){
      P1=0x55;
      delay(500);
      P1=0xaa;
      delay(500);
   }
   EX0=1;
}

void main(void)
{
   // Write your code here
   LED_ON();
   BUT_OFF();
   IRQ_INIT();
   while (1){
     switch(button_ctr){
	case 1: ;break;
	case 2: ;break;
	case 3:
	   change_flow();
	   button_ctr=0;
	   break;
	default: ;break;
      }
   }
}


//中断号
//0是外部中断
//1是定时器0
//2是外部中断1
//3是定时器1
//4是串行口
void timer0() interrupt 1{
      uchar ctr;
      TH0=(65535-50000)/256;
      TL0=(65535-50000)%256;
      ctr++;
      if(ctr==10){
	 P1=~P1;
	 ctr=0;
      }
}


void timer1(void) interrupt 0{
   if(key==0){
      delay(500);
      button_ctr++;
   }
}
